name: secondhand-trade
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - Flask==2.0.1
    - Flask-SQLAlchemy==2.5.1
    - SQLAlchemy==1.4.23
    - Pillow==8.3.1
    - Werkzeug==2.0.1 